[build]
  command = "npm run build"
  publish = "dist/cleaning-service-portfolio/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/angular-runtime"
